/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_1_floricela;

/**
 *
 * @author Flory
 */
public class VentanaFactura extends javax.swing.JFrame {

    /**
     * Creates new form VentanaFactura
     */
    public VentanaFactura() {
        initComponents();
        this.setLocationRelativeTo(null);//Coloco la ventana en el centro de la pantalla
        Label_subtotal.setVisible(false);
        Label_envio.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_principal = new javax.swing.JPanel();
        Label_nombre_factura = new javax.swing.JLabel();
        Label_cedula_factura = new javax.swing.JLabel();
        Label_total = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_detalle_compra_factura = new javax.swing.JTable();
        Label_detalle_factura = new javax.swing.JLabel();
        Label_nombre = new javax.swing.JLabel();
        Label_cedula = new javax.swing.JLabel();
        Label_agradecimiento = new javax.swing.JLabel();
        Label_subtotal = new javax.swing.JLabel();
        Label_envio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FACTURA");

        Panel_principal.setBackground(new java.awt.Color(141, 28, 61));

        Label_nombre_factura.setForeground(new java.awt.Color(255, 255, 255));
        Label_nombre_factura.setText("Nombre");

        Label_cedula_factura.setForeground(new java.awt.Color(255, 255, 255));
        Label_cedula_factura.setText("Cedula ");

        Label_total.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Label_total.setForeground(new java.awt.Color(255, 255, 255));
        Label_total.setText("Total");

        jTable_detalle_compra_factura.setBackground(new java.awt.Color(239, 184, 16));
        jTable_detalle_compra_factura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jTable_detalle_compra_factura);

        Label_detalle_factura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label_detalle_factura.setForeground(new java.awt.Color(255, 255, 255));
        Label_detalle_factura.setText("DETALLE DE SU COMPRA");

        Label_nombre.setForeground(new java.awt.Color(255, 255, 255));
        Label_nombre.setText("Nombre:");

        Label_cedula.setForeground(new java.awt.Color(255, 255, 255));
        Label_cedula.setText("Cédula:");

        Label_agradecimiento.setForeground(new java.awt.Color(255, 255, 255));
        Label_agradecimiento.setText("¡Gracias por su compra!");

        Label_subtotal.setForeground(new java.awt.Color(255, 255, 255));
        Label_subtotal.setText("Subtotal");

        Label_envio.setForeground(new java.awt.Color(255, 255, 255));
        Label_envio.setText("Envío:  ¢3000");

        javax.swing.GroupLayout Panel_principalLayout = new javax.swing.GroupLayout(Panel_principal);
        Panel_principal.setLayout(Panel_principalLayout);
        Panel_principalLayout.setHorizontalGroup(
            Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_principalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Label_detalle_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168))
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_principalLayout.createSequentialGroup()
                                .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel_principalLayout.createSequentialGroup()
                                        .addComponent(Label_cedula)
                                        .addGap(18, 18, 18)
                                        .addComponent(Label_cedula_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel_principalLayout.createSequentialGroup()
                                        .addComponent(Label_nombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Label_nombre_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_principalLayout.createSequentialGroup()
                        .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Panel_principalLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(Label_agradecimiento)
                                .addGap(112, 112, 112)
                                .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_envio, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(Panel_principalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Label_total, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))))
        );
        Panel_principalLayout.setVerticalGroup(
            Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_principalLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_nombre_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_nombre))
                .addGap(18, 18, 18)
                .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_cedula_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_cedula))
                .addGap(30, 30, 30)
                .addComponent(Label_detalle_factura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(Label_subtotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_agradecimiento)
                    .addComponent(Label_envio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_total, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_agradecimiento;
    private javax.swing.JLabel Label_cedula;
    public static javax.swing.JLabel Label_cedula_factura;
    private javax.swing.JLabel Label_detalle_factura;
    public static javax.swing.JLabel Label_envio;
    private javax.swing.JLabel Label_nombre;
    public static javax.swing.JLabel Label_nombre_factura;
    public static javax.swing.JLabel Label_subtotal;
    public static javax.swing.JLabel Label_total;
    private javax.swing.JPanel Panel_principal;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_detalle_compra_factura;
    // End of variables declaration//GEN-END:variables
}
